# Generated by Django 6.0.2 on 2026-02-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
